### ISSUE TITLE
Error when cross compiling server.

### ISSUE THREAD

**Issue by Cordain** [leptos-rs/cargo-leptos#121]
# Issue
When compiling project for `aarch64-unknown-linux-gnu` target from x86 machine, following error appears

```
Error: at `/.../cargo-leptos-0.1.8/src/compile/server.rs:36:22`

Caused by:
    0: at `/.../cargo-leptos-0.1.8/src/service/site.rs:117:44`
    1: Could not read "target/server/debug/project" at `/.../cargo-leptos-0.1.8/src/ext/fs.rs:44:10`
    2: No such file or directory (os error 2)
```

# Quickfix
Copy `debug` content of target build (ex. `target/server/aarch64-unknown-linux-gnu/debug/*`) to proposed "target/server/debug/"

# Observation
Code is ignoring information about target stored in `BinPackage` struct. If it contains value used in `.cargo/config.toml` then server executable path could be constructed with its help.

**Comment by Cordain** [comment]
After reading of `README.MD` I realized that I did not have configuration option in `cargo.toml`
```toml
[package.metadata.leptos]
bin-target-triple = "aarch64-unknown-linux-gnu"
```
It's quite confusing to me, why target configuration needs to be added in configuration file which is not meant for build target selection.  
I had configured target in `.cargo/config.toml` for binary with mind that at build time it will be picked from there, as normal cargo usage suggests. Why is it different?

**Comment by gbj** [comment]
Apologies for the delayed response here, but for anyone else reading -- much of the cargo build config here is done in the Leptos metadata section of the `Cargo.toml` because the WASM binary for the client and the server binary are built totally separately. I'm going to close this issue since, as you note, the documented behavior works as its supposed to.
