### ISSUE TITLE
'cargo leptos new' - remote rejected authentication

### ISSUE THREAD

**Issue by Viterkim** [leptos-rs/cargo-leptos#122]
Whenever i try to create a new project, i get the following.
```
cargo leptos new --git leptos-rs/start-axum
Error: Please check if the Git user / repository exists.

Caused by:
    remote rejected authentication: Failed getting response; class=Ssh (23); code=Auth (-16)
```

But my git works fine enough. 
```
git clone git@github.com:leptos-rs/cargo-leptos.git
Cloning into 'cargo-leptos'...
remote: Enumerating objects: 1652, done.
remote: Counting objects: 100% (502/502), done.
remote: Compressing objects: 100% (235/235), done.
remote: Total 1652 (delta 354), reused 298 (delta 267), pack-reused 1150
Receiving objects: 100% (1652/1652), 493.97 KiB | 1.14 MiB/s, done.
Resolving deltas: 100% (1039/1039), done.
```

SSH is fine, `cargo leptos new --git https://github.com/leptos-rs/start-axum` gives me the same result.

```
uname -a
Linux Viktor-Desktop 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux


cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.2 LTS"
```

Doing this as a workaround for now
``` 
git clone git@github.com:leptos-rs/start-axum-workspace.git
cargo leptos new --path start-axum-workspace/
```
which seems to work fow now

EDIT: ok the workspace one doesn't work (the counter, so i guess i should use https://github.com/leptos-rs/start-axum ?)

**Comment by Isti115** [comment]
I have encountered the same issue now, but recalled that I had a similar problem with cargo before, so I tried removing the following lines from my `.gitconfig`, and that made it work:
```ini
[url "git@github.com:"]
  insteadOf = https://github.com/
```

More details can be found here:
https://github.com/rust-lang/cargo/issues/8172#issuecomment-640973958

**Comment by gbj** [comment]
For anyone who runs into a similar issue, another possible solution is to use the full path of the GitHub repo, for example:
```bash
cargo leptos new --git https://github.com/leptos-rs/start-axum-workspace
```
