### ISSUE TITLE
`cargo leptos build --release` fails when using SCSS

### ISSUE THREAD

**Issue by Neighborkid01** [leptos-rs/cargo-leptos#123]
I just crated a new template project with `cargo leptos new --git leptos-rs/start-axum` and kept everything as at the defaults (aside from adding `serde` to my `Cargo.toml`).

Building the app normally without the `--release` flag worked as expected, and I can see the `start-alum.css` and `.css.map` files.
If I instead run the command with the `--release` flag, I get the error:
```bash
    Finished release [optimized] target(s) in 0.18s
       Cargo finished cargo build --package=start-axum --lib --target-dir=target/front --target=wasm32-unknown-unknown --no-default-features --features=hydrate --release
OptionParser::InvalidOption: invalid option: --no-source-map
Did you mean?  sourcemap
  Use --trace for backtrace.
Error: process css style/main.scss -> @pkg/start-axum.css at `/Users/razor_crest/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-leptos-0.1.8/src/compile/style.rs:59:10`

Caused by:
    0: Could not read to string "site/pkg/start-axum.css" at `/Users/razor_crest/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-leptos-0.1.8/src/ext/fs.rs:63:10`
    1: No such file or directory (os error 2)
```

If I rename the file to be `main.css` and update the `Cargo.toml`, then whatever processing is done to the `.scss` file is bypassed I guess, and the build completes as expected.

**Comment by niclas-ahden** [comment]
I ran into this and it turned out I had Ruby Sass on my `$PATH`:

```
$ sass --version
Ruby Sass 3.7.4
$ which sass
/Users/niclas/.asdf/shims/sass
```

That clearly isn't what `cargo-leptos` expects, but it can't tell the `sass` versions apart so it'll fail. I installed Ruby Sass _years_ ago and never uninstalled it, so that's on me. Perhaps you've got a similar issue?

**Comment by benwis** [comment]
Closing, please reopen if its still an issue
