### ISSUE TITLE
Question: What is the proper way to watch/build with tailwindcss?

### ISSUE THREAD

**Issue by niko-dunixi** [leptos-rs/cargo-leptos#128]
Hello!

I've been looking at various examples that others have put together utilizing tailwindcss, and most of them perform a `cargo leptos watch` in one terminal and in another `tailwind watch ...`.

I've been walking through this codebase and it looks like there is integrated support for tailwind:

* [src/compile/tailwind.rs](https://github.com/leptos-rs/cargo-leptos/blob/main/src/compile/tailwind.rs)
* [src/compile/style.rs](https://github.com/leptos-rs/cargo-leptos/blob/main/src/compile/style.rs) references `tailwind.rs`

It seems like one would just need to set the proper configuration in their `Cargo.toml` and then it should just work.

I tried by creating a stock application using the axum workspace example:
```bash
$ cargo leptos new --git https://github.com/Gentle/start-axum-workspace
```

Then updating/creating the various files like thus:

#### **`Cargo.toml`**
```toml
[[workspace.metadata.leptos]]
# ...
tailwind-input-file = "style/tailwind.css"
tailwind-config-file = "./tailwind.config.js"
```

#### **`tailwind.config.js`**
```javascript
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: {
    files: ["*.html", "*/src/**/*.rs"],
  },
  theme: {
    extend: {},
  },
  plugins: [],
};
```

#### **`/style/tailwind.css`**
```css
@tailwind base;
@tailwind components;
@tailwind utilities;
```

#### **`app/src/lib.rs`**
```rust
//...

#[component]
fn HomePage(cx: Scope) -> impl IntoView {
    // Creates a reactive value to update the button
    let (count, set_count) = create_signal(cx, 0);
    let on_click = move |_| set_count.update(|count| *count += 1);

    view! { cx,
        <main class="w-full h-full">
            <div class="flex flex-row">
                <h1>"foo"</h1>
                <h3>"bar"</h3>
                <button on:click=on_click>"Click Me: " {count}</button>
            </div>
        </main>
    }
}
```

But even with a full restart of `cargo leptos watch` I'm not seeing these tailwind styles get applied or get seemingly get compiled either.

Is there something I need to do to turn this on, or have I misunderstood the capabilities of the `cargo-leptos` cli?

[edited: fixing tailwind config, it was subtly wrong]

**Comment by phillipbaird** [comment]
Did you install cargo-leptos from git?  I don't think the built in support for Tailwind has been released.
The command for installing from git is in the README.

**Comment by sebastian** [comment]
Thank you @phillipbaird! Not having installed cargo-leptons from git was indeed my problem.

**Comment by KadekM** [comment]
For whomever stumbles upon this when googling like I did - if using that particular template - don't forget to add something like `"./app/**/*.rs"` to `tailwind.config.js`

**Comment by niko-dunixi** [comment]
Thank you very much, @phillipbaird ! I appreciate your help, I wouldn't have realized that this was not currently released.

@KadekM , thank you for your comment as well. I didn't realize that my tailwind config was slightly wrong. Nice catch!
