### ISSUE TITLE
Can't run the binary release on Amazon Linux 2

### ISSUE THREAD

**Issue by markcatley** [leptos-rs/cargo-leptos#131]
The binary release gets the following error when you run on Amazon Linux 2:
`/lib64/libm.so.6: version 'GLIBC_2.29' not found`

I believe this is resolved by using cargo dist which it looks like you've already set up but haven't made a release since you did that. Any chance you could do a release and see if that resolves the problem?

**Comment by akesson** [comment]
Sorry for the late reply. Please try the newly released 0.1.9

**Comment by akesson** [comment]
And please re-open the issue if it doesn't work on 0.1.9

**Comment by markcatley** [comment]
FYI @akesson, this still doesn't work due to cargo-dist not supporting this like I thought it did. I'm falling back on building as part of my deployment for now. Unfortunately, it adds about 7 minutes to a 10-minute deployment which isn't ideal.

I've opened axodotdev/cargo-dist#264 so we'll see if there's any interest in adding support over there.

Thanks a lot for being a bit more pro-active in doing releases and looking at PRs lately. It's much appreciated.

**Comment by DCNick3** [comment]
Other way to accomplish the portability would be to build static binaries with musl. This is also not yet supported by cargo-dist though
