### ISSUE TITLE
Installing cargo-leptos 0.18 fails

### ISSUE THREAD

**Issue by AdamLeyshon** [leptos-rs/cargo-leptos#134]
I see this may have already been fixed in a recent commit but trying to install `cargo-leptos` now fails with:

```text
Compiling cargo-leptos v0.1.8
error[E0308]: mismatched types
   --> /home/aleyshon/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cargo-leptos-0.1.8/src/compile/style.rs:103:18
    |
103 |         targets: browsers,
    |                  ^^^^^^^^ expected `Targets`, found `Option<Browsers>`
    |
    = note: expected struct `Targets`
                 found enum `std::option::Option<Browsers>`
help: call `Into::into` on this expression to convert `std::option::Option<Browsers>` into `Targets`
    |
103 |         targets: browsers.into(),
    |                          +++++++
```

Which is interesting because it already tries to pull in `lightningcss v1.0.0-alpha.42` but according to the lock file it should be `alpha.40` 🤷🏻‍♂️

**Comment by gbj** [comment]
Correct, this was fixed in #133 but let's leave this issue open for any others who see it. You can install the fixed version with 
```bash
cargo install cargo-leptos --git https://github.com/leptos-rs/cargo-leptos
```

**Comment by emilioziniades** [comment]
hi there @gbj ,any reason not to bump the patch version and publish a working build onto crates.io? I'd be happy to assist in doing this.

**Comment by akesson** [comment]
Version 0.1.9 should work. Please re-open the issue if it doesn't.
