### ISSUE TITLE
cargo leptos build always returns success code

### ISSUE THREAD

**Issue by ogesaku** [leptos-rs/cargo-leptos#135]
First of all, thanks for the great work on leptos and cargo-leptos!

I'm setting up CI server for a leptos build. I've just discovered that `cargo leptos build` always returns a success exit code, even if there is a compilation error.

![Screenshot 2023-06-11 at 17 53 20](https://github.com/leptos-rs/cargo-leptos/assets/26811945/9ac6675d-7170-49ac-83de-a4f5d680e6ba)

A similar (or the same) problem was issued in https://github.com/leptos-rs/cargo-leptos/issues/114. There is even an opened PR that fixes it. Could you please merge it in?

**Comment by markcatley** [comment]
Yes, it's the same issue as #114 and #115. Just needs to be reviewed and merged. I'm not convinced my fix in #115 is ideal as it runs all the builds and then fails - in retrospect I thing failing fast is probably a better solution. Happy to update the PR if anyone agrees.

**Comment by akesson** [comment]
Oh, I merged #115 
@markcatley Feel free to do a new PR with the improved solution if you want.
