### ISSUE TITLE
Failing for tailwind plugins

### ISSUE THREAD

**Issue by ogesaku** [leptos-rs/cargo-leptos#136]
Build (and watch) fails after adding plugins to `tailwind.config.js`

```js
module.exports = {
  content: {
    files: ["*.html", "./src/**/*.rs"],
  },
  plugins: [require("@tailwindcss/typography"), require("daisyui")],
};
``` 
![Screenshot 2023-06-11 at 18 24 35](https://github.com/leptos-rs/cargo-leptos/assets/26811945/cdbdfe80-7bd8-4c5f-934e-53c950d508fc)

I've installed all required dependencies locally with `npm i -D tailwindcss @tailwindcss/typography daisyui`

**Comment by ainesophaur** [comment]
The issue (at least on my machine) seems to be the colored/styled output from the plugin to stdout.

If you disable the logs it should build

```
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: {
    files: ["*.html", "*/src/**/*.rs"],
  },
  theme: {
    extend: {},
  },
  plugins: [require('daisyui')],
  daisyui: {
      logs: false,
  },
};

```

**Comment by MolotovCherry** [comment]
I was getting this too
`Error: Unexpected end of input at :1798:1`
Can confirm that disabling logs got it to compile

**Comment by ckissane** [comment]
This could be fixed/worked around on leptos end more generally by calling tailwind with the output file option `-o` to a temporary file. That way all plugins that log won't break / pollute the css output.
