### ISSUE TITLE
Wasm file name with `_bg` expected when running the generated binary resulting in 404 error.

### ISSUE THREAD

**Issue by lalanikarim** [leptos-rs/cargo-leptos#143]
When running the generated binary from `cargo leptos build` the server is expecting the wasm file with suffix of `_bg.wasm` while the generated wasm file doesn't have that suffix. This results in a 404 error and requires an additional step to either rename or create a symbolic link from `<prog-name>_bg.wasm` to `<prog-name>.wasm` in the `target/site/pkg` folder.
Is the expected behavior?
I was only able to find 1 reference to `_bg.wasm` in the leptos related code base and it was in the hydration test code linked here:
https://github.com/leptos-rs/leptos/blob/18bc03e6607acf93e7a8aa73607ba17f24bf18cf/leptos_dom/examples/hydration-test/src/main.rs#L22

**Comment by lalanikarim** [comment]
Need to do some more investigation.

**Comment by lalanikarim** [comment]
Found the code responsible for this and the reasoning: https://github.com/leptos-rs/leptos/blob/18bc03e6607acf93e7a8aa73607ba17f24bf18cf/integrations/utils/src/lib.rs#L53
Closing the issue.

**Comment by kruserr** [comment]
This behavior seems rather arbitrary, and should probably be documented somewhere, maybe a list of available env vars and their type / behaviors / etc.
