### ISSUE TITLE
Please consider removing git dependency on hot-reload

### ISSUE THREAD

**Issue by benwis** [leptos-rs/cargo-leptos#155]
The git dependency on cargo-leptos breaks the Nix build for cargo-leptos. I have a fork with just the version included. Will submit PR later

**Comment by gbj** [comment]
I'm quite sure that one's on me, sorry! Should be totally safe to use the released version.

**Comment by benwis** [comment]
> I'm quite sure that one's on me, sorry! Should be totally safe to use the released version.

Not at all, you've got a dual git/not-git dep, which Nix isn't a huge fan of. Works great for Rust

**Comment by gbj** [comment]
Just did this in 1b15c1d0823a12d2428e8a6c2a6b45bf08596df8, sorry for the delay.
