### ISSUE TITLE
upgrade dependency on libssl to use current version (3.x) instead of libssl.so.1.1

### ISSUE THREAD

**Issue by diversable** [leptos-rs/cargo-leptos#206]
The current version of cargo-leptos depends on an out-of-support version of libssl (libssl.so.1.1) - it would be greatly appreciated if cargo-leptos could update this dep to libssl3.x, so that we're using a supported version of libssl!

It would also make the cargo-leptos build tool easier to work with, since the current versions of debian & ubuntu (& other distros) currently ship with libssl3 as default.

Thanks!

"""
Note: The latest stable version is the 3.1 series supported until 14th March 2025. Also available is the 3.0 series which is a Long Term Support (LTS) version and is supported until 7th September 2026. The previous LTS version (the 1.1.1 series) is also available but has recently gone out of support. Users should transition to 3.0 or 3.1 as soon as possible.
"""
(from: https://www.openssl.org/source/)

**Comment by gbj** [comment]
Would you be interested in making a PR, or helping track down where the dependency is coming from?

**Comment by gbj** [comment]
Fair enough! I'll make a new release in the next few days.
