### ISSUE TITLE
Bump cargo-leptos to `0.2.1` in Nixpkgs?

### ISSUE THREAD

**Issue by saikatdas0790** [leptos-rs/cargo-leptos#210]
https://github.com/NixOS/nixpkgs/tree/nixos-unstable/pkgs/development/tools/rust/cargo-leptos

**Comment by saikatdas0790** [comment]
Created a pull request for this here

https://github.com/NixOS/nixpkgs/pull/265473

@benwis Tagging you since you are the maintainer for this package listed on nixpkgs :)

**Comment by benwis** [comment]
Now we wait for it to be merged
