### ISSUE TITLE
"Could not remove base" error with `CARGO_TARGET_DIR`

### ISSUE THREAD

**Issue by ensc** [leptos-rs/cargo-leptos#215]
`cargo leptos watch` fails when `CARGO_TARGET_DIR` is set.  I tried recent master (b3a556ae68cdb303b67d5919e54017c427f6983d)

1. `mkdir /tmp/test`
2. `cd /tmp/test`
3. `cargo leptos new --name project --git https://github.com/leptos-rs/start`
4. `cd /tmp/test/project`
5. `CARGO_TARGET_DIR=/tmp/test/.cache cargo leptos watch`

Results in

```
thread 'main' panicked at src/config/project.rs:217:14:
called `Result::unwrap()` on an `Err` value: Could not remove base "/tmp/test/project" from "/tmp/test/.cache/tmp"
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Error happens at https://github.com/leptos-rs/cargo-leptos/blob/b3a556ae68cdb303b67d5919e54017c427f6983d/src/config/project.rs#L213-L217

**Comment by Maneren** [comment]
This was fixed already in #159 but broke again in #200 as an additional config was added. I can try fixing it.
