### ISSUE TITLE
Unable to compile cargo-leptos on M1 pro chip using nix-shell

### ISSUE THREAD

**Issue by gravityvi** [leptos-rs/cargo-leptos#221]
Unable to compile cargo-leptos using nix shell on  a macbook M1 pro:

Error: 
```
note: ld: framework not found SystemConfiguration
       >           clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
       >           
       >
       > error: could not compile `cargo-leptos` (bin "cargo-leptos") due to previous error
```

**Comment by benwis** [comment]
On macos you need to manually provide some of the darwin only packages, in a process similar to the one described by this reddit post.
https://old.reddit.com/r/rust/comments/ptagz8/cargo_build_fails_ld_framework_not_found_security/

**Comment by benwis** [comment]
Closing, please reopen if you're still having this issue

**Comment by erikkrieg** [comment]
I'm also hitting this error (with cargo-leptos-0.2.2) M1 Mac w/ Nix:

```
ld: framework not found SystemConfiguration
clang-16: error: linker command failed with exit code 1 (use -v to see invocation)
```

I've tried adding the following to my flake without success so far:
```
buildInputs = [
  # for cargo-leptos
  darwin.apple_sdk.frameworks.Security
  darwin.apple_sdk.frameworks.SystemConfiguration
];
```

Still working on this and will follow up with another comment if I figure it out.
