### ISSUE TITLE
Cannot Create New Project from Template with .gitconfig in place

### ISSUE THREAD

**Issue by tdrozdowski** [leptos-rs/cargo-leptos#232]
A `.gitconfig` that uses `insteadOf` seems to break the new command:

```
cargo -v leptos new -v --git leptos-rs/start-axum
Error: Please check if the Git user / repository exists.

Caused by:
    invalid or unknown remote ssh hostkey; class=Ssh (23); code=Certificate (-17)
```

If I temporarily remove the `.gitconfig` I'm able to run the command.

`.gitconfig` looks like:

```
[url "ssh://git@github.com/"]
        insteadOf = https://github.com/
```

**Comment by gbj** [comment]
Maybe try using the full path to the repo insted? This is just an alias for `cargo leptos new --git https://github.com/leptos-rs/start-axum`. If that doesn't work it's likely a `cargo-generate` issue, which this command uses internally.

**Comment by tdrozdowski** [comment]
Yeah, I tried that as well and no luck.   In the short term I simply moved the file - ran it to generate my project stubs - and then put it back.

**Comment by gbj** [comment]
Does `cargo-generate` work for you with that file?

**Comment by tdrozdowski** [comment]
No it didn't.  Looking at `cargo-generate` project I see the following issue that is exactly what I hit - so will track this.  Thanks!  https://github.com/cargo-generate/cargo-generate/issues/874
