### ISSUE TITLE
Incorrect help message for very verbose option

### ISSUE THREAD

**Issue by dav-wolff** [leptos-rs/cargo-leptos#247]
Running `cargo leptos build --help` says to use the `--vv` option for very verbose output:
```
-v...
        Verbosity (none: info, errors & warnings, -v: verbose, --vv: very verbose)
```

However, running `cargo leptos build --vv` produces the following error:
```
+ command cargo leptos build --vv
error: unexpected argument '--vv' found

Usage: cargo-leptos build [OPTIONS]

For more information, try '--help'.
```

It should say to use `-vv` instead of `--vv`. The same applies to test, end-to-end, serve, and watch.

**Comment by gbj** [comment]
Thanks. Would you be interested in making a PR to fix it?

**Comment by dav-wolff** [comment]
Yes, will do
