### ISSUE TITLE
How to set the frontend library compile into wasm32

### ISSUE THREAD

**Issue by GISerliang** [leptos-rs/cargo-leptos#273]
I want use `leptos_dom::Mountable`, but this trait is available for wasm32 arch like below picture.
![image](https://github.com/leptos-rs/cargo-leptos/assets/11342604/ec74cd9d-58ec-477d-a0fc-c13c3e81e88b)

I also set toolchain in `rust-toolchain.toml` like `targets = ["wasm32-unknown-unknown"]`, but I run `cargo leptos watch` command got an error.

I want to know how to set the frontend library compile into wasm32?

**Comment by gbj** [comment]
I'm confused by the question, to be honest; as far as I know it will already compile the lib crate to wasm32. Maybe you could provide some example code and what the error is?

**Comment by GISerliang** [comment]
> I'm confused by the question, to be honest; as far as I know it will already compile the lib crate to wasm32. Maybe you could provide some example code and what the error is?


![image](https://github.com/leptos-rs/cargo-leptos/assets/11342604/02f71e6e-f05c-4314-8d11-1fa81174326f)

**Comment by gbj** [comment]
Right, so placing it in the `app.rs` that is used by both the browser/client-side (compiling from lib.rs) and from the server-side (compiling from main.rs) means that it is not available when compiling the server, hence the error. 

You should consider feature-gating the import with something like `#[cfg(feature = "hydrate")]`

**Comment by GISerliang** [comment]
> Right, so placing it in the `app.rs` that is used by both the browser/client-side (compiling from lib.rs) and from the server-side (compiling from main.rs) means that it is not available when compiling the server, hence the error.
> 
> You should consider feature-gating the import with something like `#[cfg(feature = "hydrate")]`

Could I only compile the browser/client-side?

**Comment by gbj** [comment]
> Thanks. I wiil try this method. But I also want to know could I only compile the browser/client-side?

Do you mean if you don't want a server at all? Yes, but then the cargo-leptos setup you're using is not the best, as it's specifically designed to build the server and the browser halves at once. If you're not actually using the server, then just use Trunk or wasm-pack and build a client-side app.

**Comment by GISerliang** [comment]
> Do you mean if you don't want a server at all? Yes, but then the cargo-leptos setup you're using is not the best, as it's specifically designed to build the server and the browser halves at once. If you're not actually using the server, then just use Trunk or wasm-pack and build a client-side app.

I understand you means. Thanks.
