### ISSUE TITLE
LEPTOS_HASH_FILES=true doesn't work in release mode

### ISSUE THREAD

**Issue by robert-king** [leptos-rs/cargo-leptos#277]
it works with cargo leptos watch. However, when releasing, the hash'd files aren't referenced from index.html

Here's a reproduction with the start-axum project:

`cargo leptos new --git leptos-rs/start-axum`

enter "test"

`cd test`

`LEPTOS_HASH_FILES=true cargo leptos build -r`

`cp ./target/release/test .`
`cp -r ./target/site .`

`ls site/pkg `
test.gt_CqG-CHfAyvI2psz9D4Q.wasm	test.rHvQi67cE1R_8v2ybXqdpA.js
test.kVVT6bjZUD4gNwWvLJRL7g.css

`vi x.sh`

```
export LEPTOS_OUTPUT_NAME="test"
export LEPTOS_SITE_ROOT="site"
export LEPTOS_SITE_PKG_DIR="pkg"
export LEPTOS_SITE_ADDR="127.0.0.1:3000"
export LEPTOS_RELOAD_PORT="3001"
./test
```

`bash x.sh`

go to http://127.0.0.1:3000/

fails to load the following files which are missing hash's

- /pkg/test.css
- /pkg/test.js
- /pkg/test.wasm

**Comment by robert-king** [comment]
@maccesch fyi as you might know who can help with this

**Comment by maccesch** [comment]
Have you tried adding `export LEPTOS_HASH_FILES=true` to x.sh ?

**Comment by robert-king** [comment]
@maccesch ah thanks, that fixed it (note, i also had to copy the hash.txt file across obviously).

`export LEPTOS_HASH_FILES=true`
`cp ../target/release/hash.txt .`

I'll make a pull request,
1. make it a little clearer that the env variable is needed at runtime too.
2. Add a panic if hash.txt is missing.

**Comment by robert-king** [comment]
@maccesch  one last thing i noticed is it doesn't output the hash file in the correct release folder when cross compiling

e.g. with this command

`LEPTOS_HASH_FILES=true CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER=x86_64-unknown-linux-gnu-gcc TARGET_CC=x86_64-unknown-linux-gnu-gcc LEPTOS_BIN_TARGET_TRIPLE=x86_64-unknown-linux-gnu cargo leptos build -r`

hash.txt gets generated in 
`target/release/hash.txt`
instead of in
`target/x86_64-unknown-linux-gnu/release/hash.txt`
