### ISSUE TITLE
Consider compile target when placing hash.txt

### ISSUE THREAD

**Issue by maccesch** [leptos-rs/cargo-leptos#278]
@maccesch  one last thing i noticed is it doesn't output the hash file in the correct release folder when cross compiling

e.g. with this command

`LEPTOS_HASH_FILES=true CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER=x86_64-unknown-linux-gnu-gcc TARGET_CC=x86_64-unknown-linux-gnu-gcc LEPTOS_BIN_TARGET_TRIPLE=x86_64-unknown-linux-gnu cargo leptos build -r`

hash.txt gets generated in 
`target/release/hash.txt`
instead of in
`target/x86_64-unknown-linux-gnu/release/hash.txt`

_Originally posted by @robert-king in https://github.com/leptos-rs/cargo-leptos/issues/277#issuecomment-2099469608_

**Comment by robert-king** [comment]
@maccesch @benwis  I added a pull request here
https://github.com/leptos-rs/cargo-leptos/pull/282
