### ISSUE TITLE
Setting environment variables at a project level.

### ISSUE THREAD

**Issue by cobward** [leptos-rs/cargo-leptos#286]
Environment variables set in the cargo config `[env]` section are not propagated to the server when using `cargo leptos serve`. It seems that this is an upstream `cargo` issue: https://github.com/rust-lang/cargo/issues/10094#issuecomment-1385972003. Is there a workaround for setting environment variables without requiring a manual export before running the command?

**Comment by benwis** [comment]
Depends, you could run the binary that cargo-leptos runs directly, or you could read the env variables from a .env file by including a call to dotenvy in your app

**Comment by cobward** [comment]
> you could read the env variables from a .env file by including a call to dotenvy in your app

That doesn't resolve the problem, since the environment variables need to actually be set so that a downstream library can read them from the environment itself.

> Depends, you could run the binary that cargo-leptos runs directly

IMO this is equivalent to manually exporting the environment variables, basically telling developers that they need to do something more than just running `cargo leptos serve`.

**Comment by benwis** [comment]
Judging from the issue you posted, the only workaround is to do it manually as you suggest. I am rewriting cargo-leptos, which should let you call it as a standalone exe and make this go away, but that is not ready yet
