### ISSUE TITLE
subscribe to shutdown

### ISSUE THREAD

**Issue by EmilLindfors** [leptos-rs/cargo-leptos#287]
Im trying to reload an IPC socket as my leptos project is rebuilding, thus i want to send a disconnect signal using ctrl+c. However, it seems like i cant do that using cargo-leptos, as it already subscirbes to ctrl+c and overwrites whatever i try to do. Any suggestion on how i can access the shotdown signal in cargo leptos from my leptos project?

**Comment by JesusGuzmanJr** [comment]
You can still send a ctrl-c signal to your process despite using cargo-leptos. Instead of ctrl-c'ing the cargo-leptos process, just run `pkill -SIGINT <your_bin_name>`.
