### ISSUE TITLE
Doesn't watch if the path dependency is the workspace root

### ISSUE THREAD

**Issue by luxalpa** [leptos-rs/cargo-leptos#303]
Leptos-project: `my-library/crates/website`
workspace root: `my-library`

In the above case, if the leptos project has a path dependency on the workspace root, as in `path = "../.."` it will not be able to watch the files in the workspace root's src folder. This is because in this case `unbase` will give a `"."` path buf, which is then joined to `src`, yielding `./src` as the path, which then fails the path prefix check for `src/lib.rs`

https://github.com/leptos-rs/cargo-leptos/blob/d36a1870452fceab2365df6ae16677b6573b69a3/src/ext/cargo.rs#L104-L106

**Comment by luxalpa** [comment]
PR: #304

**Comment by benwis** [comment]
Merged!
