### ISSUE TITLE
Bundle external modules to use them from JS snippets

### ISSUE THREAD

**Issue by nv0skar** [leptos-rs/cargo-leptos#311]
Hi, I'm defining JS dependencies in a `package.json` file, and then try to import them from a JS code snippet, but I can't figure out how to package those modules in `site/pkg`. Is that possible with `cargo-leptos`? Thanks for your attention!

**Comment by benwis** [comment]
Currently we do not have JS bundling built into our Rust Leptos compiling tool, I imagine you'd want to use one of the dedicated JS bundlers

**Comment by nv0skar** [comment]
I want to integrate it with `Rolldown`, I currently have a build script for my JS snippets:
```json
// package.json
{
    "type": "module",
    "scripts": {
        "build": "rolldown --config ./rolldown.config.js"
    },
    "dependencies": {
        "clientjs": "^0.2.1"
    },
    "devDependencies": {
        "rolldown": "^0.10.5",
        "daisyui": "^4.12.10"
    }
}
```

```js
// rolldown.config.js
import { defineConfig } from 'rolldown'

export default defineConfig({
    input: './app/scripts/package.js',
    output: {
        dir: './target/site/pkg/snippets/my_app-some_uid/'
    },
    resolve: {
        conditionNames: ['import'],
    }
})
```
However when using `cargo leptos build` `/target/site` is replaced with the original not bundled JS snippets. There is the possibility of writing the bundled file directly in `./app/scripts/` but I'm looking for other solutions, is it possible to pass build arguments for JS snippets when packaging the website's assets?

**Comment by nv0skar** [comment]
I resolved this by including bundled JS as assets.
