### ISSUE TITLE
Issue with VS Code and Hot Reloading

### ISSUE THREAD

**Issue by GarrettFleischer** [leptos-rs/cargo-leptos#312]
For the leptos SSR features, all the code in main.rs is disabled in the VSCode editor until I enable ```"rust-analyzer.cargo.features": "all"``` in the settings.

When running ```cargo leptos watch``` when I save a file, this seems to trigger it to rebuild a bunch of the server dependencies even when I haven't touched anything related to them.

For example start with the leptos-axum/start template. Add surrealdb as an optional dependency under the ssr feature.
save this to your VSCode settings: ```"rust-analyzer.cargo.features": "all"```
Any modifications to app.rs will then trigger a full rebuild of surrealdb.
If you comment out that vscode setting and re-run leptos, then the hot reloading will work as expected.

My guess is that enabling that in vscode is somehow causing certain files in surrealdb to be marked as "modified" and when cargo leptos is triggered it performs the rebuild.

**Comment by GarrettFleischer** [comment]
I apologize, I seem to have posted this in the wrong repo.
From info found here: https://github.com/rust-lang/rust-analyzer/issues/6136

The fix was to have my workspace settings.json look like this:
```JSON
{
    "rust-analyzer.rustfmt.overrideCommand": ["leptosfmt", "--stdin", "--rustfmt", "-c", "${workspaceFolder}/leptosfmt.toml"],
    "rust-analyzer.cargo.features": ["ssr"],
    "rust-analyzer.check.extraArgs": [
        "--target-dir", "${workspaceFolder}/target/check"
    ]
}
```

This forces cargo check to build into the target/check directory so that it doesn't invalidate the cache built by cargo leptos.

**Comment by benwis** [comment]
That’s really interesting and a potentially useful tip. You or someone should PR that to the doc section of the book
