### ISSUE TITLE
`hash_files = true` doesn't work anymore

### ISSUE THREAD

**Issue by maccesch** [leptos-rs/cargo-leptos#347]
It builds the files with the hashes in the name but then requests the files without hash.

If suspect that #345 broke non-workspace builds. Haven't tested it yet, though.

In my project I'm not setting env vars but have it configured in Cargo.toml

**Comment by benwis** [comment]
Hmm, actually reading the files is the responsibility of Leptos proper, as long as we're still setting the correct env vars. I'll have to take a look

**Comment by maccesch** [comment]
IIRC when leptos proper doesn't find the hash.txt it simply defaults to loading without hashes. So maybe that's the case here?

**Comment by benwis** [comment]
> IIRC when leptos proper doesn't find the hash.txt it simply defaults to loading without hashes. So maybe that's the case here?

Yeah, I think I've fixed that. Can you try the latest git main and lmk?

**Comment by maccesch** [comment]
I can confirm the latest git main works for my project. I suspect it won't anymore for workspace projects? I can't test that right now.

**Comment by lajtomekadimon** [comment]
I'm using workspaces, and when I try to compile WASM, I get a generic "no such file or directory" error:

```
root@d01bb3cc9efd:/srv/myproject# cargo leptos watch 
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.18s
       Cargo finished cargo build --package=myproject_server_hydration --lib --target-dir=/srv/myproject/target/front --target=wasm32-unknown-unknown --no-default-features
       Front compiling WASM
Error: No such file or directory (os error 2)
```

I didn't change anything from my project. Before upgrading to the last release, everything worked fine.

Leptos version: 0.6.14
Cargo Leptos version: lastest git main.

**Comment by benwis** [comment]
> I'm using workspaces, and when I try to compile WASM, I get a generic "no such file or directory" error:
> 
> ```
> root@d01bb3cc9efd:/srv/myproject# cargo leptos watch 
>     Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.18s
>        Cargo finished cargo build --package=myproject_server_hydration --lib --target-dir=/srv/myproject/target/front --target=wasm32-unknown-unknown --no-default-features
>        Front compiling WASM
> Error: No such file or directory (os error 2)
> ```
> 
> I didn't change anything from my project. Before upgrading to the last release, everything worked fine.
> 
> Leptos version: 0.6.14 Cargo Leptos version: lastest git main.

This is the rub, where the file is is different between the two situations. Honestly I need to detect each and do something different each time

**Comment by maccesch** [comment]
Weirdly enough I just tried to release my project to production and it simply doesn't want to load the hashed filenames. Not with versions 2.18 nor 2.19 nor latest main.

Not sure what's happening. Maybe this is a separate issue.

**Comment by maccesch** [comment]
Turns out, that was my fault.

For future reference: You need to add the env var `LEPTOS_HASH_FILES=true` when you run the built binary.

**Comment by benwis** [comment]
Closing as this should be resolved
