### ISSUE TITLE
Cloudflare Wrangler Integration

### ISSUE THREAD

**Issue by perry-birch** [leptos-rs/cargo-leptos#46]
Cloudflare workers runtime tool (wrangler) performs build, dev and publish tasks but doesn't produce an executable binary.

The Rust worker-rs bindings also require a lib to run vs a bin.

Folder structure and related Cargo.toml changes could be made to accommodate a different more desirable structure but an example project can be found here:
https://github.com/perry-birch/leptos-cloudflare

**Comment by akesson** [comment]
Could you describe exactly what you want from `cargo-leptos`?

I won't be able to put in any major effort for a few months, but if what you describe can be done without too much effort I'd be willing to consider it.

**Comment by akesson** [comment]
@perry-birch: without further input from you, I'll close this.

**Comment by akesson** [comment]
Closing this due to lack of feedback
