### ISSUE TITLE
Not linking agains lib ssl  on MacOS with brew

### ISSUE THREAD

**Issue by mclark4386** [leptos-rs/cargo-leptos#51]
I've used rustup to install `nightly` as well as `nightly-2022-12-25` and then ran `cargo install cargo-leptos` which seemed to install correctly.
However, when I try to make a project with `cargo leptos new --git https://github.com/leptos-rs/start` I get the following error:

```
dyld[60719]: Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
  Referenced from: <F3BD0A25-637A-30F9-9119-86A51CAFE7ED> /Users/mclark4386/.cargo/bin/cargo-generate
  Reason: tried: '/Users/me/.rustup/toolchains/nightly-2022-12-25-x86_64-apple-darwin/lib/libssl.1.0.0.dylib' (no such file), '/usr/local/opt/openssl/lib/libssl.1.0.0.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/openssl/lib/libssl.1.0.0.dylib' (no such file), '/usr/local/opt/openssl/lib/libssl.1.0.0.dylib' (no such file), '/usr/local/lib/libssl.1.0.0.dylib' (no such file), '/usr/lib/libssl.1.0.0.dylib' (no such file, not in dyld cache), '/Users/me/.rustup/toolchains/nightly-2022-12-25-x86_64-apple-darwin/lib/libssl.1.0.0.dylib' (no such file), '/usr/local/Cellar/openssl@1.1/1.1.1s/lib/libssl.1.0.0.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/Cellar/openssl@1.1/1.1.1s/lib/libssl.1.0.0.dylib' (no such file), '/usr/local/Cellar/openssl@1.1/1.1.1s/lib/libssl.1.0.0.dylib' (no such file), '/usr/local/lib/libssl.1.0.0.dylib' (no such file), '/usr/lib/libssl.1.0.0.dylib' (no such file, not in dyld cache)
```

I have both openssl 3.0.7 and 1.1.1 install via homebrew (I tried symlinking both to the above dylib file/location but then it gets a runtime error after putting the project name in... I'm guessing when it tries to pull some files).

**Comment by akesson** [comment]
Doesn't look related to cargo-leptos. 

Maybe try https://stackoverflow.com/questions/59006602/dyld-library-not-loaded-usr-local-opt-openssl-lib-libssl-1-0-0-dylib

**Comment by mclark4386** [comment]
That's actually the SO post I tried before posting this (thus the comments about symlinking). I posted here because I thought someone may have seen something like this before or would have some idea what's going on. 
To my untrained eye it seems either this or more likely one of it's depends are hardcoded to look for version 1.0.0 on mac.

**Comment by akesson** [comment]
Ahh sorry, read it too quickly.

Note the: 
```
Referenced from: <F3BD0A25-637A-30F9-9119-86A51CAFE7ED> /Users/mclark4386/.cargo/bin/cargo-generate
  ```

You already have cargo-generate installed, and cargo-leptos automatically uses the installed version. 
Try updating cargo-generate with: `cargo install cargo-generate` and then try running `cargo leptos new --git https://github.com/leptos-rs/start`

**Comment by mclark4386** [comment]
That was it! Thanks so much!!
