### ISSUE TITLE
name mismatch between generated config and here... should be site-address or the Cargo.toml needs to be updated.

### ISSUE THREAD

**Issue by erlandsona** [leptos-rs/cargo-leptos#64]
https://github.com/leptos-rs/cargo-leptos/blob/b227d2ba891ffd203ebfd3b0fd7fff594c429c2d/src/config/dotenvs.rs#L32

**Comment by Indrazar** [comment]
leptos-rs/start template has been updated
https://github.com/leptos-rs/start/commit/4f6e229a4dc8d47aa410dde55db5fde50c92a743

**Comment by erlandsona** [comment]
🤘🫡
