### ISSUE TITLE
cargo leptos test - not running integration tests.

### ISSUE THREAD

**Issue by phillipbaird** [leptos-rs/cargo-leptos#66]
# Problem Description

Given, a [workspace project structure](https://github.com/phillipbaird/leptos-axum-start) where the `server` contains integration tests in a `tests` directory...

```bash
/app
/front
/server
    /src
    /test
        integration.rs
```

when, you run `cargo leptos test`
then, the integration tests are not run.

# Cause

The [`build_cargo_server_cmd()`](https://github.com/leptos-rs/cargo-leptos/blob/main/src/compile/server.rs#L61-L66) function in `compiler/server.rs` always includes the `--bin` option.
For tests this restricts us to unit tests in the server binary.

# Possible Solution

One possible solution would be to change `build_cargo_server_cmd()` so that `--bin` is not included when running tests.

Thoughts?

**Comment by akesson** [comment]
The integration test folder should be named `tests`, not `test`.
https://doc.rust-lang.org/book/ch11-03-test-organization.html#integration-tests

But I assume that that's only a typo in the description. 

I haven't had much feedback regarding testing. 

There are two possible ways to do tests. The standard rust one (i.e. no target flag set) and the [wasm-bindgen one](https://rustwasm.github.io/wasm-bindgen/wasm-bindgen-test/index.html) where the `--target wasm32-unknown-unknown` is set. The first one is used by cargo-leptos. The second one runs the tests in a browser environment which is very slow and it is experimental. 

Which one are you using?

Assuming the standard rust one.

The `cargo test --help` says:
```
Options:
      --lib                                 Test only this package's library unit tests
      --bin [<NAME>]            Test only the specified binary
     --bins                               Test all binaries
```

Are you saying that when specifying the --bin it doesn't work?

**Comment by phillipbaird** [comment]
> But I assume that that's only a typo in the description.

Your assumption was correct.

> Which one are you using?

It is the standard Rust integration tests for the server that are the issue.

My [starter project](https://github.com/phillipbaird/leptos-axum-start) demonstrates the problem.  If you were to run `cargo leptos test` you will observe that no tests are run.  The one and only integration test in [`tests/integration.rs`](https://github.com/phillipbaird/leptos-axum-start/blob/main/server/tests/integration.rs) is missed.

The reasons the test is missed is because;
- each .rs file in the root of the `tests` directory is treated as as separate crate and compiled into it's own executable and...
- cargo-leptos is running the server tests with `cargo test --package=server-package --bin=server-package --target-dir=target/server --no-default-features`.  The `--bin=server-package` option says to only run tests in the server binary.  The server binary does not contain the integration tests and so the test does not get run.

This is why I think we need to remove the `--bin` option when running the server tests so that all test binaries are executed.

Let me know if I need to clarify further.

Thanks.

**Comment by akesson** [comment]
You seem to have a clear picture :)

Do you want to do a PR or do you want me to do it?

**Comment by phillipbaird** [comment]
Happy to provide a PR, just may be a day or so before I can get to it.
