### ISSUE TITLE
cargo leptos watch stop compiling when there is an error in the compiled rust code

### ISSUE THREAD

**Issue by danylaporte** [leptos-rs/cargo-leptos#72]
Step to reproduce:
1) start a new project using `cargo leptos --git ...`
2) run the project using `cargo leptos watch`
3) once the project is running, cause a compile error in any *.rs files
4) fix the error (the project does not recompile)

I can reproduce with the --locked version and the bleeding edge. 
I am on Windows 11 with the latest version of rust.

The code seems to stop responding at the following line in src/command/watch.rs

[int.recv().await.dot()?;](https://github.com/leptos-rs/cargo-leptos/blob/25b8a7e8da5043ce7e0d89971ab7128a023baa4c/src/command/watch.rs#L34)

**Comment by phillipbaird** [comment]
# Cause and Effect
1. [wait_interruptible()](https://github.com/leptos-rs/cargo-leptos/blob/main/src/ext/sync.rs#L6-L30) in sync.rs returns a boolean value.  Therefore any callers of this function cannot identify the difference between a failed compile and an interrupted compile as they both are represented by `false`.
2. Both failed and interrupted compiles are mapped to an Outcome::Stopped. See [server.rs](https://github.com/leptos-rs/cargo-leptos/blob/main/src/compile/server.rs#L27-L45) & [front.rs](https://github.com/leptos-rs/cargo-leptos/blob/main/src/compile/front.rs#L34-L36).
3. The run_loop interprets `Outcome::Stopped` as an interrupted compile not a failed compile. It therefore does not clear the change list and so future changes to the same files does not appear to be a change.  And I think this is why the recompile does not happen.

# Possible Solutions

- Introduce a new enum for `wait_interruptible()` to return with variants Success, Fail, Stopped.
Change front.rs and server.rs to map Fail and Stopped to Outcome::Success(Product::None) and Outcome::Stopped respectively.

- Alternatively we could look to reuse the current Outcome enum and maybe add a Failed variant, and return an outcome from `wait_interruptible()`.
For successful compile we'd return Outcome::Success(Product::None)
For failed compile we'd return Outcome::Failed
For interrupted compile we'd return Outcome::Stopped.
This however would then require the caller of `wait_interruptible()` (e.g. server.rs) to then check if the binary has changed and then map Outcome::Success(Product::None) to Outcome::Success(Product::Server).

Happy to create a PR if someone could kindly indicate which solution is preferred.

**Comment by akesson** [comment]
Thanks @danylaporte for reporting this.

Thanks @phillipbaird for an excellent analysis. I took the liberty to implement your first proposed solution and really hope you don't mind.
