### ISSUE TITLE
cargo leptos watch doesn't restart the server on error

### ISSUE THREAD

**Issue by eboody** [leptos-rs/cargo-leptos#83]
I wonder if this is because im on arch linux but, in a new project, if i run `cargo leptos watch` everything works correctly when I make a change that doesn't error.

but if i make a change that errors, what leptos watch outputs is 
`       Watch interrupted. Restarting build step. `
but it doesn't actually restart.

**Comment by akesson** [comment]
What version are you running? Should be fixed in 0.1.8

**Comment by eboody** [comment]
> What version are you running? Should be fixed in 0.1.8

Oh! Well I just ran `cargo leptos new --git https://github.com/leptos-rs/start`

I cant find a version number in the Cargo.toml
