### ISSUE TITLE
[Feature Request] Provide binary artifact

### ISSUE THREAD

**Issue by azzamsa** [leptos-rs/cargo-leptos#84]
Hi.

Do you plant to provide the binary artifact in the release page?

I am happy to help! 

Thank you for maintaining `cargo-leptos` :heart:

**Comment by akesson** [comment]
My focus is currently to implement tailwind support, but yes, it would be nice to have binary artefacts.

@benwis also talked about possibly contributing it. Please sync with each other to avoid double contributions :)
