### ISSUE TITLE
tailwind support not working with watch

### ISSUE THREAD

**Issue by markcatley** [leptos-rs/cargo-leptos#96]
Love that you've added tailwindcss support! Unfortunately, it seems like there's a few bugs in it.

When running `cargo leptos watch` the tailwind and you add a tailwind class that is not used anywhere else in the source code it does not work. The tailwind build should run on every change in the source code. To make it work at the moment I have to either restart the watch or go into the tailwindcss css file and make a trivial change (e.g. add a new line at the end of the file).

Tailwindcss reads all the `.rs` files, collates all the tailwind classes used and then writes a minimal css file with all those classes in it. So, if you add a class that is in a part of tailwind you haven't used before it doesn't rebuild the tailwind css so it doesn't work.

**Comment by akesson** [comment]
Closed by #98

**Comment by akesson** [comment]
Thanks for your feedback. Much appreciated. I don't use Tailwind myself, so was working a bit in blind.

**Comment by markcatley** [comment]
👍 thanks. I'll give it a test tomorrow.
