### ISSUE TITLE
[Path handling] style-file only handles files in a subfolder

### ISSUE THREAD

**Issue by akesson** [leptos-rs/cargo-leptos#99]
Turns out that the issue is the:
```toml
style-file = "./style.css"
```

It's not happy with the `./` but `style.css` doesn't work either. A workaround is to put the file in a sub-folder and use 
```toml
style-file = "style/style.css" 
```

**Comment by benwis** [comment]
This is a retro one, I think this is resolved as I've done the described behavior and cannot reproduce. Feel free to comment if it isn't
